name: app
description: "A new Flutter plugin project."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  get_it: 7.0.0
  flutter_bloc: 7.0.0

  domain:
    path: ../domain

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
