name: domain
description: "A new Flutter plugin project."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  json_serializable: 6.8.0
  build_runner: 2.4.9
  intl: 0.19.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.domain
        pluginClass: DomainPlugin
      ios:
        pluginClass: DomainPlugin
